/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finitestatemachine;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Alina
 */
public class NewJFrame extends javax.swing.JFrame {

    
    
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jtxtCheck = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtRules = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        lblAccept = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter a Word: ");

        jButton1.setText("Run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Open File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtxtRules.setColumns(20);
        jtxtRules.setLineWrap(true);
        jtxtRules.setRows(5);
        jtxtRules.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jtxtRules);

        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        lblAccept.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAccept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton5)
                                        .addGap(63, 63, 63))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblAccept, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtxtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButton2)
                        .addGap(0, 124, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:  
               
       
       String str = jtxtRules.getText();
        //Check str
        //Display error message
        if (str.isEmpty())
        {
            lblAccept.setText("Select a File");
        }
        //continue
        //Remove white spaces, letters, change a/b to digits
        //Split
        else
        {
            str = str.trim();
            str = str.toLowerCase();
            
            int startState = 1;
            //parse rules
            str = str.replaceAll("\r","");
            str = str.replaceAll("[g]","");
            str = str.replaceAll("[(]","");
            str = str.replaceAll("[)]","");
            str = str.replaceAll("[=]",",");
            str = str.trim();
            String[] Rules = str.split("\n");
            int n = Rules.length; 
            //jtxtRules.setText(str);
            int currentState = startState;
            
            //Creates a 2d array for state, char, and direction
            int[][]NewStateArr = new int[n][265];
            for (int j = 0; j <= n-1; j++)
            {
                String[] currentLine = Rules[j].split(",");
                int state = Integer.parseInt(currentLine[0]);
                char match = currentLine[1].charAt(0);
                int next = Integer.parseInt(currentLine[2]);
                NewStateArr[state][match] = next;
            }     
            
            char[][]NewCharArr = new char[n][265];
            for (int j = 0; j <= n-1; j++)
            {
                String[] currentLine = Rules[j].split(",");
                int state = Integer.parseInt(currentLine[0]);
                char match = currentLine[1].charAt(0);
                char next = currentLine[3].charAt(0);
                NewCharArr[state][match] = next;
            }     
            
            int[][]NewDirectionArr = new int[n][265];
            for (int j = 0; j <= n-1; j++)
            {
                String[] currentLine = Rules[j].split(",");
                int state = Integer.parseInt(currentLine[0]);
                char match = currentLine[1].charAt(0);
                int next = 0;
                if (currentLine[4].equals("l"))
                    next = -1;
                if (currentLine[4].equals("r"))
                    next = 1;
                NewDirectionArr[state][match] = next;
            }  
            
            //match char, change, move
            String strBuff = jtxtCheck.getText();
            int pos = 0;
            boolean found = true;
            while (found)
            {
                found = false;
                if (pos == strBuff.length())
                    strBuff = strBuff + " ";
                char curchar = strBuff.charAt(pos);
                    
                if (NewStateArr[currentState][curchar] != 0)
                {
                    String tc = Character.toString(NewCharArr[currentState][curchar]);
                    currentState = NewStateArr[currentState][curchar];
                    strBuff = strBuff.substring(0, pos) 
                            + tc
                            + strBuff.substring(pos +1, strBuff.length());
                    pos += NewDirectionArr[currentState][curchar];
                    if (pos == -1)
                    {
                        pos = 0;
                        strBuff = " " + strBuff;
                    }
                    found = true;
                }
            }                   
                         
            //if word is in language
            if (currentState == 2)       
                    lblAccept.setText("String Accepted");
            else
                lblAccept.setText("String Rejected");            
                
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        //open and read file
        //error message is needed
        StringBuilder buffer = new StringBuilder();
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("Text Document (*.txt)", new String[] { "txt" }));
        int result = fc.showOpenDialog(this);
        if (result == 0)
        {
          File file = fc.getSelectedFile();
          try
          {
            FileReader reader = new FileReader(file);
            for (int i = reader.read(); i != -1; i = reader.read())
            {
              char ch = (char)i;
              buffer.append(ch);
            }
            this.jtxtRules.setText(buffer.toString().trim());
            this.lblAccept.setText("");
          }
          catch (FileNotFoundException ex)
          {
            this.lblAccept.setText("File Not Found!!!");
          }
          catch (IOException ex)
          {
            this.lblAccept.setText("Read Error!!!");
          }
              
    }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jtxtRules.setText("");
        lblAccept.setText("");
        jtxtCheck.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jtxtCheck;
    private javax.swing.JTextArea jtxtRules;
    private javax.swing.JLabel lblAccept;
    // End of variables declaration//GEN-END:variables
}
